import json,pathlib
P=pathlib.Path(__file__).parent
rows=[
('OM01.1','Identify and label Bayer stars','bayer,constellation,position','direct','Use Bayer designations and constellation patterns to locate the eight named stars.','Practise identifying these particular stars on an unlabelled map.'),
('OM01.2','Plot six Messier galaxies','messier,dso,plotting','direct','Use catalogue recognition and remembered sky positions to place the six galaxies.','Memorise and practise the six requested galaxy locations; a topic match does not demonstrate recall.'),
('OM01.3','Draw the ecliptic','ecliptic,sky-map','direct','Recognise the ecliptic path through the mapped sky and draw it continuously.','Practise the curve on the supplied projection.'),
('OM01.4a','Locate the Sun at the eclipse','ecliptic,seasonal-sky,position','transferable','Infer the Sun’s position along the ecliptic from the date of the solar eclipse.','Combine seasonal solar position with the eclipse geometry.'),
('OM01.4b','Reconstruct the earlier Moon','moon-motion,moon-phase,plotting','transferable','Use the solar-eclipse epoch to infer the Moon’s earlier position, phase and bright-limb orientation.','Practise backward date offsets and shading the illuminated side correctly.'),
('OM02.1','Identify boundary constellations','constellation,constellation-names','direct','Identify constellations from their IAU boundaries and line patterns.','Practise boundary-based recognition, not only familiar stick figures.'),
('OM02.2a','Identify the red-square grid family','coordinates,equatorial,ecliptic,galactic','transferable','Distinguish coordinate families using their poles, equators and grid geometry.','Compare all three candidate systems; book phrase matches do not certify full galactic-grid coverage.'),
('OM02.2b','Identify the blue-circle grid family','coordinates,equatorial,ecliptic,galactic','transferable','Identify the complementary coordinate family through the marked circles.','Practise distinguishing longitude-like and latitude-like lines across coordinate systems.'),
('OM02.3','Locate the coordinate poles','coordinates,pole-view','direct','Infer the north and south poles from the convergence and symmetry of the grid.','Check pole identity for the actual grid rather than assuming celestial poles.'),
('OM02.4','Identify reference curves','ecliptic,celestial-equator,galactic','transferable','Distinguish the ecliptic, celestial equator and galactic equator on the map.','Practise recognising their relative orientations in unfamiliar projections.'),
('OM02.5','Mark both equinoxes','equinox,ecliptic,celestial-equator','direct','Locate the intersections of the ecliptic and celestial equator and distinguish the two equinoxes.','Practise deciding which intersection is vernal.'),
('OM02.6','Indicate annual solar motion','ecliptic,seasonal-sky,equinox','direct','Use the Sun’s annual eastward motion along the ecliptic at the vernal equinox.','Confirm the arrow direction after accounting for map orientation.'),
('OM02.7','Calibrate coordinate values','coordinate-measurement,coordinates,angular-scale','direct','Read and interpolate the marked grid values with the correct coordinate units.','Practise numerical calibration and longitude wrap-around.'),
('OM02.8','Identify shaded constellation regions','constellation,constellation-names,sky-map','direct','Use constellation placement and IAU abbreviations to classify the shaded regions.','Practise rejecting shaded regions absent from the supplied list.'),
('OM03.1','Infer latitude from Orion','latitude,horizontal,mercator','transferable','Combine Orion’s known geometry with the altitude–azimuth map to estimate observer latitude.','Work through the actual orientation and hemisphere inference.'),
('OM03.2','Transfer Orion to another place and date','coordinate-transform,hour-angle,sidereal,longitude,latitude,mercator','transferable','Convert the initial directions to equatorial coordinates, update observing time/location, and transform back before plotting.','Practise the complete multi-step calculation and equal-scale drawing; isolated topic knowledge is insufficient.'),
('OT01.1','Identify reference stars','bayer,constellation,sky-map','direct','Recognise the four named reference stars on the supplied map.','Timed star-identification practice is still necessary.'),
('OT01.2','Plot the coordinate target','ra,dec,coordinate-measurement,plotting','direct','Use the permitted local rectangular coordinate grid to interpolate the target position.','Practise sexagesimal conversion and interpolation on the supplied field.'),
('OT01.3','Acquire and centre the target','telescope,fov,centering','direct','Choose an eyepiece, find the target and centre it on the crosshair.','Hands-on telescope practice under the six-minute limit cannot be replaced by reading.'),
('OT02.1','Measure lensing time delays','lensing,accuracy,brightness','additional','Match the same variability features between lensed images, measure delays repeatedly and convert the movie time scale.','Additional training: feature matching in time series, repeated timing and uncertainty reduction. General measurement discussion is only transferable support.'),
('OP01.1','Rank orbital semi-major axes','orbital-period,planet-motion,accuracy','additional','Measure the apparent orbital progression and connect orbital period with semi-major axis under Kepler’s relation.','Additional training in period estimation and the Kepler period–size relation; apparent-motion discussion alone is insufficient.'),
('OP01.2','Trace trajectories and infer inclinations','inclination,ecliptic,projection,angular-scale','transferable','Trace the moving objects, measure each trajectory’s inclination to the ecliptic and combine the estimates.','Practise dome-to-map tracing and the orbital-plane geometry.'),
('OP02.1','Map moons in an unfamiliar sky','sky-map,position,plotting','transferable','Transfer four visible moon positions from an unfamiliar projected sky to its map.','Practise rapid pattern matching without relying on familiar Earth constellations.'),
('OP02.2','Reconstruct ring boundaries','ring-geometry,projection,angular-scale','additional','Translate the observed ring geometry into a scaled plan-view construction with the given illumination.','Additional training in ring and shadow geometry; generic projections are supporting skills only.'),
('OP02.3','Determine the physical ring width','ring-geometry,angular-scale,accuracy','additional','Use the reconstructed diagram and given planet radius to convert a measured width to kilometres.','First validate the ring construction; then practise scale ratios and measurement uncertainty.')]
links={k:'https://ioaa2025.in/wp-content/uploads/2025/09/Observation-'+v+'-Questions.pdf' for k,v in [('OM','SkyMap'),('OT','Telescope'),('OP','Planetarium')]}
exams=[dict(id=i,label=i+' · '+title,paper=i[:2],kind='task',concepts=['c-'+c for c in cs.split(',')],coverage=cat,reason=reason,gap=gap,url=links[i[:2]],mapping='Editorial skill interpretation of the official question; not an examiner-approved coverage rating.') for i,title,cs,cat,reason,gap in rows]
(P/'exam-data.json').write_text(json.dumps(exams,ensure_ascii=False,indent=2))
